// All editable event content is centralized here for quick future CMS/backend integration.
const WEDDING = { date: new Date('2026-11-15T09:15:00+05:30'), gallery: [
  {src:'public/images/ring-k.jpg', alt:"Krishna's initial ring"},
  {src:'public/images/ring-s.jpg', alt:"Shyam's initial ring"},
  {src:'public/images/twirl.jpg', alt:'Krishna and Shyam dancing together'},
  {src:'public/images/bride.jpg', alt:'Shyam in her wedding outfit'},
  {src:'public/images/groom.jpg', alt:'Krishna in his wedding outfit'},
  {src:'public/images/colonnade.jpg', alt:'Krishna and Shyam beneath a colonnade'}
]};

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const nav=document.querySelector('.nav');addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>80),{passive:true});
const sections=[...document.querySelectorAll('main section[id]')], links=[...document.querySelectorAll('.nav-links a')];const sectionObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-45% 0px -45%'});sections.forEach(s=>sectionObserver.observe(s));

const dialog=document.querySelector('#lightbox'),lightboxImage=document.querySelector('#lightboxImage'),count=document.querySelector('#lightboxCount');let index=0;function show(i){index=(i+WEDDING.gallery.length)%WEDDING.gallery.length;const p=WEDDING.gallery[index];lightboxImage.src=p.src;lightboxImage.alt=p.alt;count.textContent=`${index+1} / ${WEDDING.gallery.length}`;} document.querySelectorAll('.gallery-slide').forEach(b=>b.onclick=()=>{show(+b.dataset.index);dialog.showModal()});document.querySelector('#openGallery').onclick=()=>{show(0);dialog.showModal()};document.querySelector('.close').onclick=()=>dialog.close();document.querySelector('.prev').onclick=()=>show(index-1);document.querySelector('.next').onclick=()=>show(index+1);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});let x;dialog.addEventListener('touchstart',e=>x=e.changedTouches[0].screenX,{passive:true});dialog.addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-x;if(Math.abs(dx)>45)show(index+(dx<0?1:-1))},{passive:true});
const track=document.querySelector('.gallery-track'),dots=document.querySelector('.gallery-dots');WEDDING.gallery.forEach((_,i)=>{const dot=document.createElement('button');dot.setAttribute('aria-label',`Show photo ${i+1}`);dot.onclick=()=>track.querySelector(`[data-index="${i}"]`).scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});dots.append(dot)});function updateDots(){const slides=[...track.children],center=track.scrollLeft+track.clientWidth/2;let active=0,min=Infinity;slides.forEach((s,i)=>{const distance=Math.abs(s.offsetLeft+s.offsetWidth/2-center);if(distance<min){min=distance;active=i}});[...dots.children].forEach((d,i)=>d.classList.toggle('active',i===active))}track.addEventListener('scroll',updateDots,{passive:true});updateDots();document.querySelector('.gallery-prev').onclick=()=>track.scrollBy({left:-track.clientWidth*.8,behavior:'smooth'});document.querySelector('.gallery-next').onclick=()=>track.scrollBy({left:track.clientWidth*.8,behavior:'smooth'});
